package com.fixme.authservice.model;

public enum VehicleCategory {
    ALL,        // مش مهم / كل الأنواع
    GERMAN,     // BMW, Audi, VW...
    JAPANESE,   // Toyota, Honda...
    KOREAN,     // Hyundai, Kia...
    AMERICAN,   // Ford, Chevrolet...
    ELECTRIC    // سيارات كهربائية
}
